version: 2.0.4-{build}
os: Visual Studio 2015

install:
  - hg clone http://hg.libsdl.org/SDL submodules/SDL
before_build:
- cd submodules/SDL
- ps: ../../scripts/updateversion.ps1
- type include\SDL_revision.h
- cd ../../
build_script:
- ps: scripts/build_windows.ps1
deploy:
  provider: NuGet
  server: https://www.myget.org/F/devzh/
  api_key:
    secure: rZ7DEc0Com5ZMUI/4asIgqUpfXn3TgoktxT7ZzyqXaBd57XymoLtpPLyLHswtfZK
  skip_symbols: true
  artifact: /.*\.nupkg/
artifacts:
- path: '*.nupkg'
