version: 2.0.4-{build}
os: Visual Studio 2015

install:
  - git submodule update --init --recursive
build_script:
- ps: scripts/build_windows.ps1
artifacts:
- path: DevZH.SDL.Internal-Windows.2.0.4.nupkg
  name: DevZH.SDL.Internal-Windows.2.0.4.nupkg
- path: DevZH.SDL.Internal-UWP.2.0.4.nupkg
  name: DevZH.SDL.Internal-UWP.2.0.4.nupkg